meta_product_name: "Data Collection Made Easy"
meta_title: "Data Collection Made Easy - Market research and simple reports that you can manage easily"
meta_description: "Data collection made easy helps research professionals make their researches easily"
meta_image: "logo2.png" # should exist in `app/assets/images/`
